/**
 * LensMood camera stocks — the 18 signature looks, their default sliders and
 * their per-camera colour/metering character. Pure data: no Skia, no DOM.
 * Ported 1:1 from the web app's src/lib/styles.ts. Every numeric value —
 * curves, split-tones, colour matrices, grain, lens response — is byte-for-byte
 * identical to the web engine so a developed frame matches the original app.
 *
 * The only change from the web module: the shared types (CameraStyle,
 * StyleParams, StyleCharacter, LensResponse, CompositeOperation) now live in
 * `@/engine/types` instead of being declared here.
 */

import type { CameraStyle, StyleParams } from '@/engine/types'

const P = (p: Partial<StyleParams>): StyleParams => ({
  intensity: 80,
  grain: 20,
  contrast: 50,
  warmth: 50,
  flash: 0,
  shadows: 30,
  smoothing: 0,
  ...p,
})

export const CAMERA_STYLES: CameraStyle[] = [
  {
    id: 'disposable',
    exif: 'F/11 · 400 FILM · FLASH',
    name: 'Disposable Camera',
    tagline: 'Warm flash, soft grain',
    description: 'Warm flash, soft blur, imperfect exposure and that unmistakable nostalgic grain.',
    tier: 'free',
    badge: 'trending',
    defaults: P({ intensity: 85, grain: 70, contrast: 55, warmth: 68, flash: 70, shadows: 30, smoothing: 0 }),
    character: {
      // Overexposed warm party flash: +EV to the clamp, AWB asleep so the party cast survives, chunky colored grain, visible leak.
      optics: { ca: 0.55, cornerSoft: 0.5, distortion: 0.6, flareAniso: 0.55 },
      bands: { sat: [0.3, 0.15, -0.05, -0.1, 0.05, 0.1], lum: [0.08, 0.1, 0, 0, -0.08, 0] },
      lens: { meterBias: 0.85, meterStrength: 0.9, faceWeight: 0.85, awb: 0.1, awbClamp: 0.2, lightHalation: 0.9, toneMap: 0.35, dof: 0.25, autoIso: 0.85, clarity: 0, vibrance: 0.4, shadowDenoise: 0.3, skinGlow: 0.95 },
      grainSize: 1.5,
      grainAmp: 1.5,
      grainChroma: 0.7,
      colorMatrix: [1.1, 0.04, -0.14, 0.02, 1.02, -0.04, -0.06, 0.1, 0.96],
      curve: 0.3,
      leak: 0.5,
      sepia: 0.15,
      saturate: 1.12,
      brightness: 1.1,
      blur: 0.5,
      fade: 0.1,
      halation: 0.3,
      splitTone: { shadows: '#5c4020', highlights: '#ffe28a', amount: 0.5 },
      tint: { color: '#ffcf4d', alpha: 0.12, blend: 'overlay' },
    },
    cardFilter: 'brightness(1.24) saturate(1.22) sepia(0.3) contrast(1.04)',
    gradient: 'linear-gradient(135deg,#ffb84d,#ff7a59)',
  },
  {
    id: 'iphone-flash',
    exif: 'F/1.8 · ISO 640 · FLASH',
    name: 'iPhone Flash',
    tagline: 'Hard flash, deep shadows',
    description: 'Bright direct flash, sharp subject, background falling into darkness. Social-night energy.',
    tier: 'free',
    defaults: P({ intensity: 85, grain: 0, contrast: 58, warmth: 44, flash: 90, shadows: 24, smoothing: 22 }),
    character: {
      // The computational phone: hard white flash, HDR-flattened shadows, clinically clean and faintly cool.
      optics: { ca: 0.04, cornerSoft: 0.02, distortion: 0.03, flareAniso: 0.05 },
      bands: { sat: [0.08, 0.05, 0.05, 0.08, 0.12, 0.05], lum: [0.05, 0.04, 0.02, 0.04, 0.05, 0.02] },
      lens: { meterBias: 0.1, meterStrength: 0.95, faceWeight: 0.9, awb: 0.95, awbClamp: 0.45, lightHalation: 0.15, toneMap: 0.85, dof: 0.35, autoIso: 0.1, clarity: 0.3, vibrance: 0.7, shadowDenoise: 0.95, skinGlow: 0.95 },
      curve: 0.1,
      saturate: 1.12,
      brightness: 1.04,
      halation: 0.05,
      fade: 0,
      splitTone: { shadows: '#7d8494', highlights: '#eef2fb', amount: 0.2 },
      tint: { color: '#dfe8ff', alpha: 0.07, blend: 'overlay' },
      colorMatrix: [0.99, 0.02, -0.01, 0, 1, 0, -0.02, 0, 1.04],
      grainSize: 0.6,
      grainAmp: 0.5,
      grainChroma: 0,
    },
    cardFilter: 'brightness(1.18) contrast(1.06) saturate(1.04)',
    gradient: 'linear-gradient(135deg,#e8e8f2,#9aa0b4)',
  },
  {
    id: 'camcorder-90s',
    exif: 'REC · 30FPS · AUTO',
    name: '90s Camcorder',
    tagline: 'Soft tape, muted color',
    description: 'Lo-fi video softness, timestamp, scanlines, muted color and a hiss of analog noise.',
    tier: 'premium',
    defaults: P({ intensity: 85, grain: 55, contrast: 46, warmth: 47, flash: 5, shadows: 30, smoothing: 0 }),
    character: {
      // VHS tape: green-grey muted color that keeps the room's cast, smeary tube softness, chroma tape noise, slightly dim.
      optics: { ca: 0.85, cornerSoft: 0.45, distortion: 0.3, flareAniso: 0.7 },
      bands: { sat: [-0.2, -0.1, 0.05, 0, -0.1, -0.25], lum: [-0.05, 0, 0.03, 0, -0.05, -0.05] },
      lens: { meterBias: -0.15, meterStrength: 0.35, faceWeight: 0.5, awb: 0.15, awbClamp: 0.3, lightHalation: 0.5, toneMap: 0.15, dof: 0.1, autoIso: 0.85, clarity: 0, vibrance: 0, shadowDenoise: 0.1, skinGlow: 0.15 },
      colorMatrix: [0.84, 0.12, 0.01, 0.05, 1, -0.02, 0.05, 0.12, 0.78],
      splitTone: { shadows: '#2f4a3f', highlights: '#d8e6d0', amount: 0.3 },
      tint: { color: '#57705f', alpha: 0.12, blend: 'overlay' },
      curve: 0.12,
      fringe: 1.6,
      saturate: 0.62,
      brightness: 0.97,
      blur: 1.1,
      fade: 0.18,
      halation: 0.18,
      grainSize: 1.6,
      grainAmp: 1.5,
      grainChroma: 0.8,
      scanlines: true,
      timestamp: true,
    },
    cardFilter: 'sepia(0.2) hue-rotate(60deg) saturate(0.7) contrast(0.98) brightness(0.98) blur(0.4px)',
    gradient: 'linear-gradient(135deg,#7de0b8,#3d8f9f)',
  },
  {
    id: 'leica-street',
    exif: 'F/2 · ISO 400 · 35MM',
    name: 'Leica Street',
    tagline: 'Clean contrast, quiet grain',
    description: 'Clean contrast, honest skin tones, a whisper of film grain. Pure editorial street.',
    tier: 'free',
    defaults: P({ intensity: 80, grain: 22, contrast: 62, warmth: 47, flash: 0, shadows: 38, smoothing: 0 }),
    character: {
      // Honest reportage: neutral-cool restraint with decisive true blacks, crisp micro-contrast, quiet grain.
      optics: { ca: 0.03, cornerSoft: 0.06, distortion: 0.02, flareAniso: 0.05 },
      bands: { sat: [0.05, -0.05, -0.1, 0, 0.05, -0.1], lum: [-0.05, 0, -0.05, 0, -0.04, 0] },
      lens: { meterBias: -0.2, meterStrength: 0.5, faceWeight: 0.6, awb: 0.9, awbClamp: 0.4, lightHalation: 0.2, toneMap: 0.1, dof: 0.45, autoIso: 0.35, clarity: 0.5, vibrance: 0.15, shadowDenoise: 0.25, skinGlow: 0.1 },
      colorMatrix: [0.97, 0.02, 0.01, 0, 1, 0, 0, 0.03, 0.99],
      curve: 0.5,
      saturate: 0.92,
      brightness: 1,
      fade: 0,
      halation: 0,
      grainSize: 0.85,
      grainAmp: 0.7,
      grainChroma: 0.15,
    },
    cardFilter: 'grayscale(0.12) contrast(1.28) saturate(0.88) brightness(0.96)',
    gradient: 'linear-gradient(135deg,#3c3c46,#c8c8d2)',
  },
  {
    id: 'gq-editorial',
    exif: 'F/8 · ISO 100 · STROBE',
    name: 'GQ Editorial',
    tagline: 'Polished light, crisp shadows',
    description: 'Luxury magazine lighting, crisp shadows, polished skin. You, but on a newsstand.',
    tier: 'premium',
    defaults: P({ intensity: 85, grain: 6, contrast: 66, warmth: 62, flash: 30, shadows: 55, smoothing: 45 }),
    character: {
      // Bronze magazine strobe: polished warm-metallic skin, gold split-tone glamour, deep controlled grainless shadows.
      optics: { ca: 0.04, cornerSoft: 0.05, distortion: 0, flareAniso: 0.08 },
      bands: { sat: [0.15, 0.1, -0.3, -0.15, -0.05, 0.05], lum: [0.02, 0.1, -0.08, -0.05, -0.12, -0.04] },
      lens: { meterBias: 0.15, meterStrength: 0.9, faceWeight: 0.9, awb: 0.7, awbClamp: 0.4, lightHalation: 0.4, toneMap: 0.35, dof: 0.85, autoIso: 0.1, clarity: 0.3, vibrance: 0.35, shadowDenoise: 0.8, skinGlow: 0.8 },
      colorMatrix: [1.08, 0.04, -0.12, 0.03, 1, -0.03, -0.02, 0.08, 0.9],
      splitTone: { shadows: '#2b1a08', highlights: '#f5c96a', amount: 0.6 },
      curve: 0.4,
      saturate: 1.05,
      brightness: 1.04,
      fade: 0,
      halation: 0.14,
      grainSize: 0.6,
      grainAmp: 0.5,
      grainChroma: 0.1,
      tint: { color: '#c9862e', alpha: 0.14, blend: 'soft-light' },
    },
    cardFilter: 'sepia(0.35) saturate(1.25) contrast(1.2) brightness(1.05)',
    gradient: 'linear-gradient(135deg,#e8c877,#9a6b2f)',
  },
  {
    id: 'a24-still',
    exif: 'F/2.8 · ISO 800 · 1/48',
    name: 'A24 Movie Still',
    tagline: 'Muted color, soft highlights',
    description: 'Cinematic shadows, muted palette, soft highlights. Quiet, moody, devastating.',
    tier: 'free',
    badge: 'featured',
    defaults: P({ intensity: 82, grain: 34, contrast: 46, warmth: 38, flash: 0, shadows: 55, smoothing: 0 }),
    character: {
      // Cold melancholia: teal-green shadows, muted desaturated palette, lifted matte blacks and faded highlights.
      optics: { ca: 0.08, cornerSoft: 0.2, distortion: 0.03, flareAniso: 0.3 },
      bands: { sat: [-0.15, -0.2, -0.1, 0.1, 0.05, -0.25], lum: [-0.02, 0, 0, 0.05, 0.02, -0.05] },
      lens: { meterBias: -0.25, meterStrength: 0.4, faceWeight: 0.6, awb: 0.55, awbClamp: 0.35, lightHalation: 0.5, toneMap: 0.85, dof: 0.6, autoIso: 0.6, clarity: 0, vibrance: 0, shadowDenoise: 0.15, skinGlow: 0.05 },
      colorMatrix: [0.9, 0.08, 0.02, 0.02, 0.96, 0.02, 0.04, 0.08, 0.88],
      splitTone: { shadows: '#1e5f5a', highlights: '#c8cfc4', amount: 0.65 },
      curve: 0.15,
      saturate: 0.72,
      brightness: 0.98,
      fade: 0.42,
      halation: 0.1,
      grainSize: 1.1,
      grainAmp: 1.1,
      grainChroma: 0.3,
      tint: { color: '#1f4f4a', alpha: 0.16, blend: 'overlay' },
    },
    cardFilter: 'sepia(0.25) hue-rotate(140deg) saturate(0.65) contrast(0.92) brightness(1.03)',
    gradient: 'linear-gradient(135deg,#3f6f78,#1d2a33)',
  },
  {
    id: 'film-noir',
    exif: 'F/5.6 · ISO 400 · B&W',
    name: 'Film Noir',
    tagline: 'Hard light, deep blacks',
    description: 'Black and white, hard shadows, dramatic contrast. Vintage mystery in every frame.',
    tier: 'premium',
    defaults: P({ intensity: 88, grain: 44, contrast: 86, warmth: 50, flash: 10, shadows: 76, smoothing: 0 }),
    character: {
      // Hard-boiled silver gelatin: meters for the highlights, shadows die inky, grain rises as the bar gets darker.
      bw: true,
      curve: 0.85,
      brightness: 0.96,
      fade: 0,
      halation: 0.2,
      grainSize: 1.15,
      grainAmp: 1.15,
      grainChroma: 0,
      splitTone: { shadows: '#0b0e18', highlights: '#f4f4f0', amount: 0.12 },
      optics: { ca: 0.08, cornerSoft: 0.5, distortion: 0.05, flareAniso: 0.45 },
      lens: { meterBias: -0.8, meterStrength: 0.9, faceWeight: 0.85, awb: 0, awbClamp: 0.3, toneMap: 0, shadowDenoise: 0, vibrance: 0, autoIso: 0.75, clarity: 0.5, dof: 0.5, skinGlow: 0.35, lightHalation: 0.9 },
    },
    cardFilter: 'grayscale(1) contrast(1.6) brightness(0.9)',
    gradient: 'linear-gradient(135deg,#f2f2f2,#101014)',
  },
  {
    id: 'y2k-digicam',
    exif: 'F/2.6 · ISO 200 · FLASH',
    name: 'Y2K Digicam',
    tagline: 'Glossy flash, bright color',
    description: 'Harsh flash, glossy highlights, slight overexposure. Early-2000s party immortality.',
    tier: 'premium',
    badge: 'trending',
    defaults: P({ intensity: 88, grain: 55, contrast: 62, warmth: 42, flash: 78, shadows: 22, smoothing: 0 }),
    character: {
      // Lo-fi CCD: blown highlights, cyan-shifted whites, smeary oversaturation, fringing and crunchy chroma noise.
      optics: { ca: 0.95, cornerSoft: 0.4, distortion: 0.5, flareAniso: 0.5 },
      bands: { sat: [0.2, 0.15, 0.25, 0.4, 0.3, 0.3], lum: [0.05, 0.05, 0, 0.1, 0, 0.05] },
      lens: { meterBias: 0.6, meterStrength: 0.75, faceWeight: 0.7, awb: 0.15, awbClamp: 0.2, lightHalation: 0.9, toneMap: 0, dof: 0.05, autoIso: 0.9, clarity: 0, vibrance: 0.85, shadowDenoise: 0, skinGlow: 0.8 },
      curve: 0.15,
      hue: -5,
      saturate: 1.35,
      brightness: 1.12,
      blur: 0.35,
      fade: 0.08,
      halation: 0.45,
      fringe: 1.2,
      splitTone: { shadows: '#2e4a44', highlights: '#c9fff2', amount: 0.5 },
      tint: { color: '#aef2e2', alpha: 0.1, blend: 'screen' },
      colorMatrix: [0.9, 0.12, -0.02, 0.02, 1, 0, 0, 0.08, 0.94],
      grainSize: 1,
      grainAmp: 1.6,
      grainChroma: 0.9,
    },
    cardFilter: 'brightness(1.22) saturate(1.5) contrast(1.04) hue-rotate(12deg) blur(0.3px)',
    gradient: 'linear-gradient(135deg,#7ad7ff,#c65cff)',
  },
  {
    id: 'polaroid',
    exif: 'F/8 · 600 FILM · INSTANT',
    name: 'Polaroid',
    tagline: 'Creamy light, faded color',
    description: 'Creamy highlights, soft faded color, instant-film frame. Warmth you can hold.',
    tier: 'free',
    defaults: P({ intensity: 85, grain: 22, contrast: 40, warmth: 64, flash: 24, shadows: 18, smoothing: 12 }),
    character: {
      // Instant film: creamy overexposed warmth, cyan-drifting shadows, milky bloomed highlights, gentle low contrast.
      optics: { ca: 0.2, cornerSoft: 0.7, distortion: 0.1, flareAniso: 0.2 },
      bands: { sat: [-0.08, 0.08, -0.12, 0.15, 0.05, -0.05], lum: [0.06, 0.08, 0, 0.03, 0.05, 0.02] },
      lens: { meterBias: 0.3, meterStrength: 0.65, faceWeight: 0.75, awb: 0.35, awbClamp: 0.25, lightHalation: 0.85, toneMap: 0.3, dof: 0.3, autoIso: 0.3, clarity: 0, vibrance: 0.08, shadowDenoise: 0.25, skinGlow: 0.6 },
      colorMatrix: [1.06, 0.02, -0.04, 0.02, 1, -0.02, -0.02, 0.06, 0.9],
      splitTone: { shadows: '#1e6f6f', highlights: '#ffe8c4', amount: 0.55 },
      tint: { color: '#ffdfae', alpha: 0.1, blend: 'soft-light' },
      curve: 0.1,
      sepia: 0.12,
      saturate: 0.82,
      brightness: 1.07,
      blur: 0.45,
      fade: 0.4,
      halation: 0.3,
      grainSize: 0.9,
      grainAmp: 0.7,
      grainChroma: 0.2,
      polaroidFrame: true,
    },
    cardFilter: 'sepia(0.28) saturate(0.9) brightness(1.1) contrast(0.88)',
    gradient: 'linear-gradient(135deg,#fff2dc,#f0b8a0)',
  },
  {
    id: 'super-8',
    exif: 'REC · 18FPS · 8MM',
    name: 'Super 8',
    tagline: 'Warm grain, home-movie glow',
    description: 'Faded warmth, thick grain and a soft flicker of light. Summers that never ended.',
    tier: 'premium',
    defaults: P({ intensity: 85, grain: 72, contrast: 56, warmth: 78, flash: 0, shadows: 62, smoothing: 0 }),
    character: {
      // 1970s home movie: dim amber cast over everything, big soft grain, gate-weave blur, dark corners — vintage warm-dark.
      optics: { ca: 0.5, cornerSoft: 0.85, distortion: 0.25, flareAniso: 0.5 },
      bands: { sat: [0.18, 0.25, -0.1, -0.25, -0.2, -0.05], lum: [0.05, 0.08, 0, -0.1, -0.15, -0.05] },
      lens: { meterBias: -0.35, meterStrength: 0.5, faceWeight: 0.5, awb: 0.05, awbClamp: 0.15, lightHalation: 0.6, toneMap: 0.1, dof: 0.2, autoIso: 0.8, clarity: 0, vibrance: 0.05, shadowDenoise: 0.2, skinGlow: 0.3 },
      grainSize: 1.7,
      grainAmp: 1.6,
      grainChroma: 0.35,
      colorMatrix: [1.06, 0.06, -0.12, 0.04, 1, -0.04, -0.02, 0.08, 0.94],
      curve: 0.35,
      leak: 0.35,
      sepia: 0.35,
      saturate: 0.92,
      brightness: 0.94,
      blur: 1.1,
      fade: 0.18,
      halation: 0.3,
      splitTone: { shadows: '#3d2314', highlights: '#ffcf7d', amount: 0.5 },
      tint: { color: '#e8a04c', alpha: 0.2, blend: 'multiply' },
    },
    cardFilter: 'sepia(0.48) saturate(1.05) brightness(0.88) contrast(1.06) blur(0.3px)',
    gradient: 'linear-gradient(135deg,#ffc46b,#d96f32)',
  },
  {
    id: 'lomo',
    exif: 'F/2.8 · 400 FILM · ZONE',
    name: 'Lomo',
    tagline: 'Punchy color, dark corners',
    description: 'Oversaturated color, crushed vignette corners and happy accidents. Toy-camera magic.',
    tier: 'free',
    badge: 'new',
    defaults: P({ intensity: 90, grain: 44, contrast: 74, warmth: 46, flash: 0, shadows: 92, smoothing: 0 }),
    character: {
      // Cross-processed slide: crushed cyan-green shadows, magenta-hot mids, vibrance maxed, heavy vignette — toxic-colorful.
      optics: { ca: 0.8, cornerSoft: 0.9, distortion: 0.8, flareAniso: 0.6 },
      bands: { sat: [0.35, 0.25, 0.4, 0.35, 0.3, 0.4], lum: [0.05, 0, -0.12, -0.05, -0.15, 0.05] },
      lens: { meterBias: -0.1, meterStrength: 0.3, faceWeight: 0.55, awb: 0.2, awbClamp: 0.2, lightHalation: 0.6, toneMap: 0, dof: 0.3, autoIso: 0.6, clarity: 0.25, vibrance: 1, shadowDenoise: 0, skinGlow: 0.4 },
      grainSize: 1.1,
      grainAmp: 1.2,
      grainChroma: 0.6,
      colorMatrix: [1.12, -0.18, 0.06, -0.06, 1.1, -0.04, 0.1, -0.14, 1.04],
      curve: 0.6,
      fringe: 2.2,
      leak: 0.45,
      saturate: 1.4,
      hue: -12,
      brightness: 1,
      fade: 0,
      halation: 0.15,
      splitTone: { shadows: '#0e5c4a', highlights: '#ff4fa3', amount: 0.85 },
      tint: { color: '#0f6b52', alpha: 0.14, blend: 'overlay' },
    },
    cardFilter: 'saturate(1.6) contrast(1.35) hue-rotate(-14deg) brightness(0.97)',
    gradient: 'linear-gradient(135deg,#37c978,#0e5a46)',
  },
  {
    id: 'kodachrome',
    exif: 'F/5.6 · K64 SLIDE · 1/125',
    name: 'Kodachrome',
    tagline: 'Rich color, clean shadows',
    description: 'The slide film that shot the sixties — dense reds, honest light, shadows that hold.',
    tier: 'premium',
    defaults: P({ intensity: 88, grain: 14, contrast: 72, warmth: 56, flash: 0, shadows: 52, smoothing: 0 }),
    character: {
      // Dense slide film: meters for the highlights, inky shadows, red-forward dye density with biting micro-contrast.
      optics: { ca: 0.1, cornerSoft: 0.12, distortion: 0.04, flareAniso: 0.15 },
      bands: { sat: [0.4, 0.18, 0.12, -0.05, 0.15, 0.22], lum: [-0.22, -0.08, -0.12, -0.05, -0.18, -0.15] },
      lens: { meterBias: -0.5, meterStrength: 0.7, faceWeight: 0.5, awb: 0.25, awbClamp: 0.2, lightHalation: 0.3, toneMap: 0.05, dof: 0.45, autoIso: 0.15, clarity: 0.45, vibrance: 0.15, shadowDenoise: 0.2, skinGlow: 0.35 },
      grainSize: 0.65,
      grainAmp: 0.7,
      grainChroma: 0.2,
      curve: 0.6,
      colorMatrix: [1.18, -0.1, -0.05, -0.05, 1.08, -0.04, -0.03, -0.1, 1.08],
      splitTone: { shadows: '#641414', highlights: '#fcd34d', amount: 0.5 },
      saturate: 1.3,
      brightness: 0.97,
      fade: 0,
      halation: 0.05,
      tint: { color: '#d33a2a', alpha: 0.1, blend: 'multiply' },
    },
    cardFilter: 'saturate(1.5) contrast(1.35) brightness(0.9) sepia(0.15) hue-rotate(-5deg)',
    gradient: 'linear-gradient(135deg,#e8534a,#8f2d1e)',
  },
  {
    id: 'security-cam',
    exif: 'CAM 02 · 12FPS · IR',
    name: 'Security Cam',
    tagline: 'Grainy green, timestamped',
    description: 'Fluorescent wash, analog noise and a running timestamp. Caught on tape, forever.',
    tier: 'premium',
    defaults: P({ intensity: 88, grain: 80, contrast: 72, warmth: 38, flash: 30, shadows: 45, smoothing: 0 }),
    character: {
      // CCTV: cold green near-monochrome, dead crushed shadows, gained-up contrast, heavy mono noise, IR-hot faces.
      optics: { ca: 0.3, cornerSoft: 0.6, distortion: 0.85, flareAniso: 0.2 },
      bands: { sat: [-0.3, -0.25, 0, -0.1, -0.3, -0.35], lum: [0, 0, 0.05, 0, -0.05, -0.05] },
      lens: { meterBias: 0.1, meterStrength: 0.8, faceWeight: 0.4, awb: 0.95, awbClamp: 0.5, lightHalation: 0.9, toneMap: 0, dof: 0, autoIso: 1, clarity: 0.5, vibrance: 0, shadowDenoise: 0.2, skinGlow: 0.9 },
      colorMatrix: [0.3, 0.55, 0.05, 0.1, 0.95, 0.1, 0.1, 0.55, 0.15],
      splitTone: { shadows: '#03170c', highlights: '#c8ffd8', amount: 0.5 },
      tint: { color: '#39ff88', alpha: 0.14, blend: 'overlay' },
      curve: 0.5,
      saturate: 0.12,
      brightness: 1.02,
      blur: 0.5,
      fade: 0,
      halation: 0.3,
      grainSize: 1.3,
      grainAmp: 2,
      grainChroma: 0.15,
      scanlines: true,
      timestamp: true,
    },
    cardFilter: 'grayscale(0.85) sepia(0.9) hue-rotate(75deg) saturate(1.6) contrast(1.3) brightness(1.02)',
    gradient: 'linear-gradient(135deg,#7de8a9,#2e4d3a)',
  },
  {
    id: 'point-shoot',
    exif: 'F/1.8 · 1.0″ CMOS · 24MM',
    name: 'Point & Shoot',
    tagline: 'Crisp flash, glossy color',
    description:
      'The pocket vlogger’s compact — hard little flash, glossy color, detail that bites. Every night out looks like a press event.',
    tier: 'premium',
    badge: 'new',
    defaults: P({ intensity: 85, grain: 12, contrast: 72, warmth: 32, flash: 92, shadows: 72, smoothing: 0 }),
    character: {
      // The 2000s compact: harsh cold bluish flash, biting oversharpened detail, background crushed to deep black.
      optics: { ca: 0.3, cornerSoft: 0.15, distortion: 0.3, flareAniso: 0.45 },
      bands: { sat: [0.1, 0.05, 0.1, 0.15, 0.2, 0.1], lum: [0, 0, -0.05, 0, -0.05, -0.1] },
      lens: { meterBias: -0.25, meterStrength: 0.5, faceWeight: 0.9, awb: 0.55, awbClamp: 0.35, lightHalation: 0.3, toneMap: 0, dof: 0.1, autoIso: 0.25, clarity: 0.8, vibrance: 0.5, shadowDenoise: 0.55, skinGlow: 0.9 },
      curve: 0.45,
      saturate: 1.1,
      brightness: 1.02,
      halation: 0.08,
      fade: 0,
      splitTone: { shadows: '#0a1220', highlights: '#e8f2ff', amount: 0.45 },
      tint: { color: '#c8dcff', alpha: 0.1, blend: 'overlay' },
      colorMatrix: [0.98, 0.04, -0.02, -0.02, 1, 0.02, -0.02, -0.02, 1.08],
      grainSize: 0.6,
      grainAmp: 0.7,
      grainChroma: 0.15,
    },
    cardFilter: 'contrast(1.32) brightness(1.05) sepia(0.28) hue-rotate(190deg) saturate(1.25)',
    gradient: 'linear-gradient(135deg,#d8dee8,#2a2e36)',
  },
  {
    id: 'pastel-cinema',
    exif: 'F/4 · ISO 100 · SYM',
    name: 'Pastel Cinema',
    tagline: 'Powdery color, flat light',
    description: 'Flat storybook light and powdery pastels. Every frame arranged just so.',
    tier: 'free',
    defaults: P({ intensity: 85, grain: 8, contrast: 32, warmth: 54, flash: 0, shadows: 4, smoothing: 28 }),
    character: {
      // Milky daydream: overexposes into high key, shadows opened and matted grey-pink, powder color under a soft glow.
      optics: { ca: 0.05, cornerSoft: 0.3, distortion: 0, flareAniso: 0.2 },
      bands: { sat: [-0.2, -0.12, -0.18, -0.08, -0.1, -0.05], lum: [0.08, 0.06, 0.05, 0.05, 0.05, 0.06] },
      lens: { meterBias: 0.25, meterStrength: 0.9, faceWeight: 0.8, awb: 0.85, awbClamp: 0.4, lightHalation: 0.4, toneMap: 0.9, dof: 0.5, autoIso: 0.05, clarity: 0, vibrance: 0, shadowDenoise: 0.85, skinGlow: 0.45 },
      grainSize: 0.7,
      grainAmp: 0.5,
      grainChroma: 0.15,
      curve: 0,
      splitTone: { shadows: '#c4a7b8', highlights: '#fff1e8', amount: 0.4 },
      saturate: 0.78,
      brightness: 1.06,
      blur: 0.35,
      fade: 0.22,
      halation: 0.35,
      tint: { color: '#ffdbe4', alpha: 0.16, blend: 'screen' },
    },
    cardFilter: 'brightness(1.12) contrast(0.84) saturate(0.7) sepia(0.08)',
    gradient: 'linear-gradient(135deg,#ffd7e0,#b8e6d9)',
  },
  {
    id: 'tokyo-neon',
    exif: 'F/1.4 · ISO 1600 · NIGHT',
    name: 'Tokyo Neon',
    tagline: 'Neon bloom, wet streets',
    description: 'Pink and cyan bloom on wet pavement, blacks that swallow the rest. 2 a.m. forever.',
    tier: 'premium',
    badge: 'trending',
    defaults: P({ intensity: 90, grain: 30, contrast: 74, warmth: 34, flash: 0, shadows: 70, smoothing: 0 }),
    character: {
      // Night neon: drags every scene toward a 2 a.m. key, keeps the colored light, blue-black shadows, glowing magenta/cyan lamps.
      optics: { ca: 0.4, cornerSoft: 0.2, distortion: 0.08, flareAniso: 0.85 },
      bands: { sat: [0.1, -0.15, -0.2, 0.35, 0.35, 0.4], lum: [0, -0.05, -0.1, 0.1, 0.05, 0.12] },
      lens: { meterBias: -0.85, meterStrength: 0.9, faceWeight: 0.4, awb: 0.05, awbClamp: 0.15, lightHalation: 1, toneMap: 0, dof: 0.5, autoIso: 0.85, clarity: 0.25, vibrance: 0.35, shadowDenoise: 0, skinGlow: 0.25 },
      grainSize: 1,
      grainAmp: 1.1,
      grainChroma: 0.6,
      curve: 0.5,
      colorMatrix: [1.02, -0.08, 0.08, -0.05, 0.98, 0.07, 0.05, -0.05, 1.04],
      splitTone: { shadows: '#1e1b4b', highlights: '#f56bff', amount: 0.85 },
      fringe: 1.8,
      saturate: 1.35,
      hue: -12,
      brightness: 0.94,
      halation: 0.55,
      fade: 0.06,
      blur: 0.15,
      tint: { color: '#312e81', alpha: 0.14, blend: 'multiply' },
    },
    cardFilter: 'saturate(1.5) contrast(1.3) brightness(0.85) hue-rotate(-14deg)',
    gradient: 'linear-gradient(135deg,#22d3ee,#e879f9)',
  },
  {
    id: 'photobooth',
    exif: 'STRIP · 4 FRAMES · B&W',
    name: 'Photobooth',
    tagline: 'Hard flash, true black & white',
    description: 'Curtain, flash, four frames. High-key black and white that flatters everyone.',
    tier: 'free',
    badge: 'new',
    defaults: P({ intensity: 82, grain: 30, contrast: 34, warmth: 50, flash: 74, shadows: 8, smoothing: 26 }),
    character: {
      // High-key strip-booth flash: overexposes every scene to milky bright greys, flattens depth, faces first.
      bw: true,
      curve: 0.12,
      brightness: 1.05,
      fade: 0.16,
      halation: 0.2,
      blur: 0.25,
      grainSize: 0.9,
      grainAmp: 0.8,
      grainChroma: 0,
      optics: { ca: 0.15, cornerSoft: 0.3, distortion: 0.1, flareAniso: 0.1 },
      lens: { meterBias: 0.25, meterStrength: 0.95, faceWeight: 1, awb: 0, awbClamp: 0.3, toneMap: 0.85, shadowDenoise: 0.4, vibrance: 0, autoIso: 0.15, clarity: 0, dof: 0.15, skinGlow: 0.9, lightHalation: 0.3 },
    },
    cardFilter: 'grayscale(1) brightness(1.18) contrast(0.95)',
    gradient: 'linear-gradient(135deg,#ffffff,#3a3a42)',
  },
  {
    id: 'tintype',
    exif: 'WET PLATE · 5S EXP',
    name: 'Tintype 1900',
    tagline: 'Sepia plate, deep vignette',
    description: 'Wet-plate sepia, scratched edges, a vignette like candlelight. Portraits that outlive you.',
    tier: 'premium',
    defaults: P({ intensity: 90, grain: 68, contrast: 62, warmth: 56, flash: 16, shadows: 88, smoothing: 0 }),
    character: {
      // Wet-plate collodion: meterless box camera, dark sepia-silver, blown glowing highlights, crushed plate corners.
      bw: false,
      sepia: 0.9,
      saturate: 0.55,
      brightness: 0.97,
      curve: 0.55,
      blur: 0.55,
      fade: 0.1,
      halation: 0.5,
      grainSize: 1.8,
      grainAmp: 1.5,
      grainChroma: 0,
      splitTone: { shadows: '#1a120c', highlights: '#e9d5a4', amount: 0.5 },
      tint: { color: '#3a2a16', alpha: 0.14, blend: 'multiply' },
      optics: { ca: 0.1, cornerSoft: 1, distortion: 0.05, flareAniso: 0.6 },
      lens: { meterBias: 0, meterStrength: 0.3, faceWeight: 0.5, awb: 0, awbClamp: 0.3, toneMap: 0, shadowDenoise: 0.2, vibrance: 0, autoIso: 0.35, clarity: 0.25, dof: 0.3, skinGlow: 0.85, lightHalation: 0.85 },
    },
    cardFilter: 'sepia(1) saturate(0.8) contrast(1.25) brightness(0.88)',
    gradient: 'linear-gradient(135deg,#c9a05c,#4a321b)',
  },
]

export const getStyle = (id: string | null | undefined): CameraStyle | undefined =>
  CAMERA_STYLES.find((s) => s.id === id)

export interface QuickPreset {
  id: string
  name: string
  apply: (d: StyleParams) => StyleParams
}

const clamp = (v: number) => Math.max(0, Math.min(100, Math.round(v)))

export const QUICK_PRESETS: QuickPreset[] = [
  {
    id: 'natural',
    name: 'Natural',
    apply: (d) => ({
      ...d,
      intensity: 52,
      grain: clamp(d.grain * 0.55),
      smoothing: clamp(d.smoothing + 8),
    }),
  },
  {
    id: 'strong',
    name: 'Push',
    apply: (d) => ({
      ...d,
      intensity: 100,
      grain: clamp(d.grain + 14),
      contrast: clamp(d.contrast + 10),
      shadows: clamp(d.shadows + 10),
    }),
  },
  {
    id: 'viral',
    name: 'Punch',
    apply: (d) => ({
      ...d,
      intensity: 92,
      flash: clamp(d.flash + 24),
      grain: clamp(d.grain + 8),
      warmth: clamp(d.warmth + 5),
      contrast: clamp(d.contrast + 8),
    }),
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    apply: (d) => ({
      ...d,
      intensity: 86,
      shadows: clamp(d.shadows + 20),
      contrast: clamp(d.contrast + 5),
      warmth: clamp(d.warmth - 6),
      grain: clamp(d.grain + 6),
    }),
  },
  {
    id: 'editorial',
    name: 'Editorial',
    apply: (d) => ({
      ...d,
      intensity: 74,
      smoothing: clamp(d.smoothing + 26),
      contrast: clamp(d.contrast + 10),
      grain: clamp(d.grain * 0.4),
      shadows: clamp(d.shadows + 8),
    }),
  },
]

/** compact param encoding for shareable transformation links */
const PARAM_ORDER: (keyof StyleParams)[] = [
  'intensity',
  'grain',
  'contrast',
  'warmth',
  'flash',
  'shadows',
  'smoothing',
]

export const encodeParams = (p: StyleParams): string => PARAM_ORDER.map((k) => p[k]).join('.')

export function decodeParams(raw: string | null): StyleParams | null {
  if (!raw) return null
  const parts = raw.split('.').map(Number)
  if (parts.length !== PARAM_ORDER.length || parts.some((n) => !Number.isFinite(n))) return null
  const p = {} as StyleParams
  PARAM_ORDER.forEach((k, i) => {
    p[k] = Math.max(0, Math.min(100, Math.round(parts[i])))
  })
  return p
}

export const GENERATION_STEPS = [
  'Reading lighting…',
  'Rebuilding color profile…',
  'Matching camera mood…',
  'Adding grain…',
  'Developing…',
]
